### PR TITLE
update

### PR DESCRIPTION
**Pull request by black23**

### CODE REVIEW

**Review by AndrewIsh — COMMENTED** [review]
I'm puzzled why you're submitting this as a PR since these changes already exist in master?

**Comment by AndrewIsh** [comment]
Sorry, I didn't realise you'd just appended the last commit onto your last PR. That's not necessary since those changes are already in master and would be merged if your translation work was merged.

However, as grateful as I am for your translation and PR, I do not see how I can merge it since it will wipe out the English language version. Currently the ILL backends do not have the ability to support multiple languages. I would suggest creating another branch, but that might become a maintanance burden. I'm inclined to keep this PR around in anticipation of multilingual support somewhere down the line, it would be a terrible waste for your work to not be used.

**Comment by black23** [comment]
I just wanted to merge official master into our translated fork. I'm sorry if I make it bad. If transtation will be supported, I'll send czech translation.

**Comment by AndrewIsh** [comment]
Hi. No worries :) At some point I'm assuming we will add translation support, I couldn't say when though I'm afraid. In the meantime, it's good to know we've got a Czech translation ready :) I'll close this PR now.

**Pull request closed without merging**
