### PR TITLE
Add basic fields to other.inc

### PR DESCRIPTION
**Pull request by mkstephens**
Add fields for title, author, editor, publisher, place of publication, year, part/edition, volume, pages, ISBN, and DOI to form for "Other" request type.

### CODE REVIEW

**Comment by AndrewIsh** [comment]
This one is up for debate I think. When we created the "other" form, our customers were happier to have no fields defined and then they defined what they wanted on their copy of the FreeForm backend. But, equally, I can see having basic fields defined could be desirable. The problem could be, since it's a fallback form, there's no "right" selection of fields...

**Comment by mkstephens** [comment]
I agree that there is no "right" selection of fields for a fallback form. The main issue with not having any fields in a fallback form is that it loses its effectiveness as a fallback for an OpenURL query string.

The case for our library: I've encoded an OpenURL query string for use with EBSCO Discovery Service so that a link to place an ILL request will send the user to a pre-populated Free Form ILL form. The portion that specifies type is:
`&type={IfNotEmpty({IfEqual({PUBTYPE},Book,ok)},book,{IfNotEmpty({IfEqual({PUBTYPE},Academic+Journal,ok)},article,{IfNotEmpty({IfEqual({PUBTYPE},Dissertation/Thesis,ok)},thesis,other)})})}`
EBSCO has several more publication types, but the top three for our users are book, academic journal, and dissertation/thesis. A request for any other publication type would be directed to "Other." This worked just fine in the 18.05 branch when all the fields were persistent regardless of the type selected. Now that fields are being created based on type, any request for a publication type that is not book, journal article, or dissertation/thesis directs the user to a blank "Other" form without fields and not pre-populated with data.

What about trying to give everyone the best of both worlds? Keep "Other" as an empty template where all the fields can be created from scratch and add a new type that could function as a fallback for libraries who need it. It could be called "Default" or "Generic." 

I'm happy to revise this pull request if you're agreeable.

**Comment by mkstephens** [comment]
@AndrewIsh, I've decided for the interim to use the article type as a fallback for the OpenURL query string. It contains the highest number of common fields for a request that doesn't match the pubtypes I've included in the string. As a result, I'm anticipating it will be more difficult to identify fake article requests and further develop the query string. I continue to be a proponent of an alternative type with basic fields included in the form to serve as a fallback.

There will be a discussion about this at Koha-US in a couple of weeks. I will keep this pull request open in the meantime and will comment again after the conference.

**Comment by mkstephens** [comment]
I'm closing this pull request. After discussion at Koha-US, it seems a better path forward is to keep "Other" blank and to create a new form/request type populated with some basic fields to act as a fallback form. Will be submitting a new pull request with these changes soon.

**Pull request closed without merging**
